#define LINE_SENSOR_COUNT 48
#define POLL_RATE 1
#define KICK_MINIMUM_INTERVAL 5000
#define TUSB_VID 0x2E8A
#define TUSB_PID 0x000A
#define IS_BOTTOM_PICO
// #define IS_MIDDLE_PICO
// #define IS_TOP_PICO
#define PING_PACKET_MAX_SIZE 128
#define MOTOR_MIN_ZERO_TO_FULL_SPEED_TIME 10000; // seconds
