#ifndef USB_MAX_PACKET_SIZE
#define USB_MAX_PACKET_SIZE 1024
#endif

#ifndef USB_TX_BUFSIZE
#define USB_TX_BUFSIZE USB_MAX_PACKET_SIZE
#endif
#ifndef USB_RX_BUFSIZE
#define USB_RX_BUFSIZE USB_MAX_PACKET_SIZE
#endif

#ifndef PICO_STDIO_USB_RESET_INTERFACE_SUPPORT_MS_OS_20_DESCRIPTOR
#define PICO_STDIO_USB_RESET_INTERFACE_SUPPORT_MS_OS_20_DESCRIPTOR 1
#endif
